// frontend/src/components/job/JobRoleEditor.jsx
import { useState } from "react";
import ExternalLink from "../ui/ExternalLink";

export default function JobRoleEditor({ job, onUpdate }) {
  const [isEditingRoleLink, setIsEditingRoleLink] = useState(false);
  const [editRole, setEditRole] = useState("");
  const [editLink, setEditLink] = useState("");

  const handleStartEditRoleLink = () => {
    setEditRole(job.role);
    setEditLink(job.link || "");
    setIsEditingRoleLink(true);
  };

  const handleSaveRoleLink = () => {
    setIsEditingRoleLink(false);
    if (editRole !== job.role || editLink !== (job.link || "")) {
      onUpdate({ ...job, role: editRole, link: editLink });
    }
  };

  const handleCancelRoleLink = () => {
    setIsEditingRoleLink(false);
  };

  return isEditingRoleLink ? (
    <div
      className="flex flex-col gap-1 w-full min-w-0"
      onBlur={(e) => {
        if (!e.currentTarget.contains(e.relatedTarget)) {
          handleSaveRoleLink();
        }
      }}
      onKeyDown={(e) => {
        if (e.key === "Escape") handleCancelRoleLink();
        if (e.key === "Enter" && !e.shiftKey) {
          e.preventDefault();
          handleSaveRoleLink();
        }
      }}
    >
      <input
        autoFocus
        type="text"
        className="bg-white dark:bg-slate-800 px-2 py-1 border border-slate-300 dark:border-slate-600 rounded outline-none w-full text-slate-800 dark:text-slate-200 text-sm"
        value={editRole}
        onChange={(e) => setEditRole(e.target.value)}
        placeholder="Role"
      />
      <input
        type="url"
        className="bg-white dark:bg-slate-800 px-2 py-1 border border-slate-300 dark:border-slate-600 rounded outline-none w-full text-blue-600 dark:text-blue-400 text-xs"
        value={editLink}
        onChange={(e) => setEditLink(e.target.value)}
        placeholder="Link"
      />
    </div>
  ) : (
    <>
      <span
        onDoubleClick={handleStartEditRoleLink}
        className="p-1 border border-transparent truncate"
      >
        {job.role}
      </span>
      {job.link && (
        <ExternalLink
          href={job.link}
          className="ml-1 text-blue-400 hover:text-blue-300 text-xs truncate transition-colors"
        />
      )}
    </>
  );
}

// frontend/src/lib/components/job/job-role-editor.svelte
<script>
  import ExternalLink from "$lib/components/custom/external-link.svelte";

  let { job, onUpdate } = $props();

  let isEditingRoleLink = $state(false);
  let editRole = $state("");
  let editLink = $state("");

  function handleStartEditRoleLink() {
    editRole = job.role;
    editLink = job.link || "";
    isEditingRoleLink = true;
  }

  function handleSaveRoleLink() {
    isEditingRoleLink = false;
    if (editRole !== job.role || editLink !== (job.link || "")) {
      onUpdate({ ...job, role: editRole, link: editLink });
    }
  }

  function handleCancelRoleLink() {
    isEditingRoleLink = false;
  }

  function onBlur(e) {
    if (!e.currentTarget.contains(e.relatedTarget)) {
      handleSaveRoleLink();
    }
  }

  function onKeyDown(e) {
    if (e.key === "Escape") handleCancelRoleLink();
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSaveRoleLink();
    }
  }
</script>

{#if isEditingRoleLink}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="flex w-full min-w-0 flex-col gap-1" onblur={onBlur} onkeydown={onKeyDown}>
    <!-- svelte-ignore a11y_autofocus -->
    <input
      autofocus
      type="text"
      class="w-full rounded border border-slate-300 bg-white px-2 py-1 text-sm text-slate-800 outline-none dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200"
      bind:value={editRole}
      placeholder="Role"
    />
    <input
      type="url"
      class="w-full rounded border border-slate-300 bg-white px-2 py-1 text-xs text-blue-600 outline-none dark:border-slate-600 dark:bg-slate-800 dark:text-blue-400"
      bind:value={editLink}
      placeholder="Link"
    />
  </div>
{:else}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <span ondblclick={handleStartEditRoleLink} class="truncate border border-transparent p-1">
    {job.role}
  </span>
  {#if job.link}
    <ExternalLink
      href={job.link}
      class="ml-1 truncate text-xs text-blue-400 transition-colors hover:text-blue-300"
    />
  {/if}
{/if}
