// frontend/src/lib/components/custom/success-popup.svelte
<script>
  import Button from "./button.svelte";
  import { onMount, onDestroy } from "svelte";

  let { isOpen, onclose, title = "Successfully Saved!", message } = $props();

  function handleKeyDown(e) {
    if (!isOpen) return;
    if (e.key === "Enter" || e.key === "Escape") onclose?.();
  }

  onMount(() => {
    window.addEventListener("keydown", handleKeyDown);
  });

  onDestroy(() => {
    window.removeEventListener("keydown", handleKeyDown);
  });
</script>

{#if isOpen}
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
    <div
      class="mx-4 w-full max-w-sm rounded-xl border-2 border-green-500 bg-white p-6 text-center shadow-xl dark:bg-slate-900"
    >
      <h3 class="font-pixel mb-5 font-bold tracking-wider text-green-400 uppercase">
        {title}
      </h3>
      {#if message}
        <p class="mb-6 font-mono text-sm break-all text-slate-700 dark:text-slate-300">
          {message}
        </p>
      {/if}
      <div class="flex justify-center">
        <Button theme="green" onclick={onclose}>OK</Button>
      </div>
    </div>
  </div>
{/if}

// frontend/src/components/ui/SuccessPopup.jsx
import { useEffect } from "react";
import { createPortal } from "react-dom";
import { Button } from "./Button";

export default function SuccessPopup({
  isOpen,
  onClose,
  title = "Successfully Saved!",
  message,
}) {
  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (e) => {
      if (e.key === "Enter" || e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return createPortal(
    <div className="z-50 fixed inset-0 flex justify-center items-center bg-black/60">
      <div className="bg-white dark:bg-slate-900 shadow-xl mx-4 p-6 border-2 border-green-500 rounded-xl w-full max-w-sm text-center">
        <h3 className="mb-5 font-pixel font-bold text-green-400 uppercase tracking-wider">
          {title}
        </h3>
        {message && (
          <p className="mb-6 font-mono text-slate-700 dark:text-slate-300 text-sm break-all">
            {message}
          </p>
        )}
        <div className="flex justify-center">
          <Button theme="green" onClick={onClose}>
            OK
          </Button>
        </div>
      </div>
    </div>,
    document.body,
  );
}
